import './globals.css'


export const metadata = {
  title: 'Food cart',
  description: 'Generated by create next app',
}
const theb = {
  backgroundImage: "url('/images/winter.jpg')",
  backgroundRepeat: "no-repeat",
  backgroundSize: "cover",
  // backgroundColor: " rgba(0, 0, 0, 0.755)",
  backgroundBlendMode: "overlay",
  backgroundAttachment: "fixed",
  zIndex: 1
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='lg:h-screen lg:flex lg:justify-center lg:items-center text-white' style={theb}>
        <p className='text-[0px] lg:text-[30px] lg:flex lg:justify-center lg:font-extrabold lg:capitalize'>use a smaller screen</p>
        </div>
        <div className=' overflow-x-hidden shadow-2xl min-w-[360px] min-h-full sm:w-[100%] 
        sm:h-[100%] md:w-[100%] md:h-[100%] lg:hidden 
         xl:hidden 2xl:hidden'>
        {children}
        </div>
        </body>
    </html>
  )
}
